"""Exports collected inspection samples into a YOLO-format training dataset.

Output structure:
    <out_dir>/
        dataset.yaml               — ultralytics dataset descriptor
        images/
            train/  val/           — JPEG images
        labels/
            train/  val/           — YOLO txt annotation files (one per image)

Each annotation file contains one line per wire detection:
    <class_id> <cx> <cy> <w> <h>   (all values 0–1, relative to image dimensions)

Classes:
    0 = ok
    1 = fail

The per-wire final_result (post manual override) is used as the label
so human corrections feed back into the training data.

Usage (via CLI script):
    python scripts/export_collected_data.py --out /tmp/yolo_ds --split 0.8
"""
from __future__ import annotations

import json
import logging
import random
import shutil
from pathlib import Path

log = logging.getLogger(__name__)

CLASSES = ["ok", "fail"]

DATASET_YAML_TMPL = """\
# Auto-generated by saasa exporter
path: {abs_path}
train: images/train
val: images/val

nc: {nc}
names: {names}
"""


class DatasetExporter:
    """Builds a YOLO-format dataset from collected samples stored on disk."""

    def __init__(self, storage_root: str | Path) -> None:
        self._root = Path(storage_root)

    def export(
        self,
        out_dir: str | Path,
        train_split: float = 0.8,
        seed: int = 42,
    ) -> Path:
        """Export all collected samples to `out_dir`.

        Args:
            out_dir:      Destination directory (created if absent).
            train_split:  Fraction of samples for training; remainder goes to val.
            seed:         Random seed for reproducible splits.

        Returns:
            Path to the generated dataset.yaml.
        """
        out = Path(out_dir)
        for sub in ["images/train", "images/val", "labels/train", "labels/val"]:
            (out / sub).mkdir(parents=True, exist_ok=True)

        samples = self._collect_samples()
        if not samples:
            log.warning("No collected samples found under %s", self._root)
            return out / "dataset.yaml"

        random.seed(seed)
        random.shuffle(samples)
        split_idx = max(1, int(len(samples) * train_split))
        train_samples = samples[:split_idx]
        val_samples = samples[split_idx:]

        for sample_path, split in [(p, "train") for p in train_samples] + \
                                   [(p, "val") for p in val_samples]:
            self._export_sample(sample_path, out, split)

        yaml_path = self._write_dataset_yaml(out)
        log.info("Exported %d train / %d val samples → %s",
                 len(train_samples), len(val_samples), yaml_path)
        return yaml_path

    # ------------------------------------------------------------------
    # Internals
    # ------------------------------------------------------------------

    def _collect_samples(self) -> list[Path]:
        """Return all metadata.json files found under storage_root."""
        return sorted(self._root.rglob("metadata.json"))

    def _export_sample(self, meta_path: Path, out: Path, split: str) -> None:
        sample_dir = meta_path.parent
        meta = json.loads(meta_path.read_text())

        inspection_id = meta.get("inspection_id", sample_dir.name)
        frame_jpg = sample_dir / "frame.jpg"
        if not frame_jpg.exists():
            log.debug("Skipping %s — no frame.jpg", sample_dir)
            return

        img_name = f"{inspection_id}_frame.jpg"
        dst_img = out / "images" / split / img_name
        shutil.copy2(frame_jpg, dst_img)

        # Build YOLO label lines from wire detections
        label_lines = self._build_labels(meta, frame_jpg)
        if label_lines is None:
            return

        lbl_name = f"{inspection_id}_frame.txt"
        (out / "labels" / split / lbl_name).write_text("\n".join(label_lines))

        # Also export per-wire crop images for potential classifier retraining
        for wire in meta.get("wires", []):
            wn = wire.get("wire_no")
            crop_src = sample_dir / f"wire_{wn}.jpg"
            if not crop_src.exists():
                continue
            # Classify folder by final_result for easy classifier training
            final = wire.get("final_result") if wire.get("final_result") is not None \
                    else meta.get("final_result")
            label = "ok" if final == 1 else "fail"
            crop_dst_dir = out / "crops" / split / label
            crop_dst_dir.mkdir(parents=True, exist_ok=True)
            shutil.copy2(crop_src, crop_dst_dir / f"{inspection_id}_wire_{wn}.jpg")

    def _build_labels(self, meta: dict, frame_jpg: Path) -> list[str] | None:
        """Build YOLO-format label lines from metadata wire entries."""
        try:
            from PIL import Image
            img_w, img_h = Image.open(frame_jpg).size
        except Exception:
            log.debug("Could not read frame size for %s — skipping labels", frame_jpg)
            return None

        lines: list[str] = []
        for wire in meta.get("wires", []):
            bbox = wire.get("bbox")
            if not bbox or len(bbox) < 4:
                continue
            x, y, w, h = bbox
            # final_result per wire, fallback to inspection-level final_result
            final = wire.get("final_result")
            if final is None:
                final = meta.get("final_result")
            cls_id = 0 if final == 1 else 1  # 0=ok, 1=fail

            # Normalise to 0–1 relative to frame
            cx = (x + w / 2) / img_w
            cy = (y + h / 2) / img_h
            nw = w / img_w
            nh = h / img_h
            lines.append(f"{cls_id} {cx:.6f} {cy:.6f} {nw:.6f} {nh:.6f}")

        return lines

    def _write_dataset_yaml(self, out: Path) -> Path:
        yaml_path = out / "dataset.yaml"
        yaml_path.write_text(
            DATASET_YAML_TMPL.format(
                abs_path=str(out.resolve()),
                nc=len(CLASSES),
                names=str(CLASSES),
            )
        )
        return yaml_path
